version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"    # RabbitMQ server port
      - "15673:15672"  # RabbitMQ management UI
    networks:
      - app-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 3

  mysql:
    image: mysql:8.0.40
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 3

  order-service:
    image: lehaiduy2003/server-order-service:latest
    ports:
      - "3002:3002"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    env_file:
      - ./order-service/.env
    volumes:
      - ./order-service:/app
    command: >
      sh -c "npx prisma migrate deploy && npm run dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 5s
      timeout: 20s
      retries: 3
  general-services:
    image: lehaiduy2003/server-general-services:latest
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    env_file:
      - ./general-services/.env
    volumes:
      - ./general-services:/app
    command: >
      sh -c "npx prisma migrate deploy && npm run seed && npm run dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 5s
      timeout: 20s
      retries: 3

  gateway:
    image: lehaiduy2003/server-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - order-service
      - general-services
    networks:
      - app-network
    volumes:
      - ./gateway:/app

networks:
  app-network:
    driver: bridge
volumes:
  mysql-volume:
  rabbitmq_data:
