http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  orderService:
    host: localhost
    paths: ["/order/*", "/order"]
  generalServices:
    host: localhost
    paths: ["/general/*"]
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  orderService:
    url: http://localhost:3002/api/v1
  generalServices:
    url: http://localhost:3001/api/v1
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  orderPipeline:
    apiEndpoints:
      - orderService
    policies:
      - proxy:
          - action:
              serviceEndpoint: orderService
              changeOrigin: true
              stripPath: true
  generalPipeline:
    apiEndpoints:
      - generalServices
    policies:
      - proxy:
          - action:
              serviceEndpoint: generalServices
              changeOrigin: true
              stripPath: true
